<a href="https://colab.research.google.com/github/kaiqueg-costa/video_game_sales/blob/main/VG_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introdução (TL;DR)

*O videogame, também conhecido como jogo eletrônico, surgiu em meados de 1958 em um laboratório de pesquisas de bombas atômicas. Na sua forma mais primitiva, o jogo baseava-se em duas traços e uma bola. No entanto, o responsável pelo programa não se deu conta da importância de sua criação, então William Higinbotham não é, oficialmente, o criador do primeiro videogame.*

*Mais de meio século depois, é difícil encontrar alguém que não jogue nenhum jogo. E para isso, não é mais necessário um aparelho de video game. Os jogos podem ser instalados no videogame, celular, computadores e até mesmo TVs.* 

*Contudo, o objetivo dessa análise consiste na exploração e interpretação dos dados de vendas de jogos ao longo dos anos e quais as plataformas e genêros mais comuns, além da regionalidade de cada um. A partir disso, será possível complementar a história resumida acima através dos dados.*

<img src="https://thumbs2.imgbox.com/cb/99/B0vaedEY_t.png" width="400px" height="400px" align="center">

Fontes: 
- https://www.infoescola.com/curiosidades/historia-do-videogame/
- https://www.uol.com.br/start/ultimas-noticias/2017/02/26/inventor-do-primeiro-videogame-tambem-foi-um-dos-criadores-da-bomba-atomica.htm
- https://www.kaggle.com/datasets/gregorut/videogamesales

### Problema Fictício

A empresa JogosJogados quer desenvolver um novo game, porém, para isso eles querem realizar um estudo de mercado com os dados de jogos já lançados. A ideia é entender qual a melhor região para o lançamento, o tipo de jogo, plataforma, e etc. Com base nos dados observados no dataset, vamos tentar responder as perguntas abaixo

|  Item | Pergunta | Como |
|:--|:--|:--|
| 1 | Como é o histórico de vendas por região? | Gráfico de Linha - X: Ano - Y: Contagem de vendas por região |
| 2 | Os jogos possuem vendas iguais entre os continentes? | Gráfico de Linhas - X: Ano/jogo - Y: Contagem de vendas por região |
| 3 | Quais jogos geram mais dinheiro? | Gráfico de Barra ou Boxplot - X: Jogos - Y: Soma dos valores ou Medidas de posição e dispersão |
| 4 | Os demais continentes estão agrupados porque possuem um coportamento de gastos diferente? | Gráfco de Linha |
| 5 | Nos demais continentes, há um padrão? Uma tendência de crescimento? | Gráfico de Linha |
| 6 | Quais são os jogos mais vendidos? | Gráfico de Barra ou Boxplot |
| 7 | O mais vendido está em crescimento ou queda? | Gráfico de Linha |
| 8 | Quais jogos estão com as vendas em queda? | Gráfico de Linha |
| 9 | Qual o ano com mais vendas? | Sumarização |
| 10 | Qual desenvolvedora teve mais vendas no último ano? Qual o movimento da existência dela? | Sumarização |
| 11 | Qual plataforma teve mais vendas? Qual foi o movimento da existência dela? | Gráfico de Linha - Plataforma/Ano |
| 12 | Quantos jogos são lançados por ano? | Tabela de Frequência |
| 13 | Como é o movimento de lançamento de jogos ao longo dos anos? Está aumentando? | Gráfico de Linha |
| 14 | Quais são as plataformas mais utilizadas? | Gráfico de Linha |
| 15 | Ao longo dos anos, quantas plataformas novas são lançadas? Está crescendo? | Gráfico de Linha |
| 16 | A média de vendas nos continentes são iguais? | Teste Estatístico Paramétrico/Não Paramétrico - Medidas de Posição/Dispersão/Distribuição Normal/Teorema Limite Central|
| 17 | Como é o histórico de vendas na América do Norte? | |

## Importação das Bibliotecas e Dados

In [61]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
import plotly.io as pio

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Estudos/Projetos/vgsales.csv')

In [4]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

## Entender a Estrutura do Dataset

### Dicionário de Dados

|  Variável | Descrição | Tipo | Pensamentos | Comentários
|:--|:--|:--|:--|:--|
| Rank | Ranking de vendas gerais | Qualitativa Ordinal |
| Name | Nome do jogo  | Qualitativa Nominal |
| Plataform | Plataforma de lançamento do jogo (PC, PS4, etc) | Qualitativa Nominal |
| Year | Ano de lançamento do jogo  | Qualitativa Nominal |
| Genre | Genêro do jogo  | Qualitativa Nominal |
| Publisher | Empresa desenvolvedora do jogo  | Qualitativa Nominal |
| NA_Sales | Vendas na América do Norte <b>em milhões</b>  | Quantitativa Contínua |
| EU_Sales | Vendas na Europa <b>em milhões</b>  | Quantitativa Contínua |
| JP_Sales | Vendas no Japão <b>em milhões</b>  | Quantitativa Contínua |
| Other_Sales | Vendas no resto do mundo <b>em milhões</b>  | Quantitativa Contínua |
| Global_Sales | Total de vendas (somatória das colunas anteriores) <b>em milhões</b>  | Quantitativa Contínua |

### Dúvidas sobre o dataset

| Item | Pergunta | Resposta |
|:--|:--|:--|
| 1 | Qual critério está sendo considerado na coluna ranking? | A coluna Global_Sales, ou seja, o total arrecadado em milhões |
| 2 | Os jogos se repetem? | Sim. Pois há jogos lançados em diferentes anos, mas com mesmo nome e também porque um mesmo jogo foi disponibilizado em diferentes plataformas. |
| 3 | Tem linhas em branco? | Sim. Nas colunas Year e Publisher, porém, os registros onde o valor dessas colunas é nulo, o restante das colunas estão preenchidas corretamente.|
| 4 | As variáveis estã armazenadas em uma única coluna? | Não. Para cada continente há uma coluna de vendas. |

1. Qual critério está sendo considerado na coluna ranking?

In [5]:
data.groupby(['Rank', 'Name'])['Global_Sales'].sum().nlargest(10)

Rank  Name
1     Wii Sports                   82.74
2     Super Mario Bros.            40.24
3     Mario Kart Wii               35.82
4     Wii Sports Resort            33.00
5     Pokemon Red/Pokemon Blue     31.37
6     Tetris                       30.26
7     New Super Mario Bros.        30.01
8     Wii Play                     29.02
9     New Super Mario Bros. Wii    28.62
10    Duck Hunt                    28.31
Name: Global_Sales, dtype: float64

2. Os jogos se repetem?

In [6]:
data.groupby(['Name'])['Name'].count().nlargest(10)

Name
Need for Speed: Most Wanted     12
FIFA 14                          9
LEGO Marvel Super Heroes         9
Madden NFL 07                    9
Ratatouille                      9
Angry Birds Star Wars            8
Cars                             8
FIFA 15                          8
FIFA Soccer 13                   8
LEGO Harry Potter: Years 5-7     8
Name: Name, dtype: int64

In [7]:
data.loc[data['Name'].isin(['Need for Speed: Most Wanted', 'FIFA 14'])].sort_values(['Name', 'Platform'])

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
6661,6663,FIFA 14,3DS,2013.0,Sports,Electronic Arts,0.00,0.23,0.00,0.03,0.25
4503,4505,FIFA 14,PC,2013.0,Sports,Electronic Arts,0.01,0.36,0.00,0.06,0.43
112,113,FIFA 14,PS3,2013.0,Sports,Electronic Arts,0.78,4.32,0.07,1.73,6.90
493,494,FIFA 14,PS4,2013.0,Sports,Electronic Arts,0.61,1.85,0.11,0.33,2.90
7034,7036,FIFA 14,PSP,2013.0,Sports,Electronic Arts,0.00,0.16,0.00,0.07,0.23
3988,3990,FIFA 14,PSV,2013.0,Sports,Electronic Arts,0.11,0.25,0.01,0.13,0.50
4538,4540,FIFA 14,Wii,2013.0,Sports,Electronic Arts,0.00,0.38,0.00,0.05,0.43
256,257,FIFA 14,X360,2013.0,Sports,Electronic Arts,0.92,2.93,0.01,0.46,4.31
1698,1700,FIFA 14,XOne,2013.0,Sports,Electronic Arts,0.41,0.66,0.00,0.12,1.19
6278,6280,Need for Speed: Most Wanted,DS,2005.0,Racing,Electronic Arts,0.24,0.01,0.00,0.02,0.27
6492,6494,Need for Speed: Most Wanted,GBA,2005.0,Racing,Electronic Arts,0.19,0.07,0.00,0.00,0.26
3585,3587,Need for Speed: Most Wanted,GC,2005.0,Racing,Electronic Arts,0.43,0.11,0.00,0.02,0.56
5900,5902,Need for Speed: Most Wanted,PC,2005.0,Racing,Electronic Arts,0.02,0.23,0.00,0.05,0.30
11676,11678,Need for Speed: Most Wanted,PC,2012.0,Racing,Electronic Arts,0.00,0.06,0.00,0.02,0.08
252,253,Need for Speed: Most Wanted,PS2,2005.0,Racing,Electronic Arts,2.03,1.79,0.08,0.47,4.37
498,499,Need for Speed: Most Wanted,PS3,2012.0,Racing,Electronic Arts,0.71,1.51,0.06,0.61,2.89
1742,1744,Need for Speed: Most Wanted,PSV,2012.0,Racing,Electronic Arts,0.38,0.52,0.01,0.25,1.16
6149,6151,Need for Speed: Most Wanted,WiiU,2013.0,Racing,Electronic Arts,0.14,0.12,0.00,0.02,0.28
1173,1175,Need for Speed: Most Wanted,X360,2012.0,Racing,Electronic Arts,0.62,0.80,0.01,0.15,1.58
1530,1532,Need for Speed: Most Wanted,X360,2005.0,Racing,Electronic Arts,1.00,0.17,0.02,0.10,1.29
2005,2007,Need for Speed: Most Wanted,XB,2005.0,Racing,Electronic Arts,0.53,0.46,0.00,0.05,1.04

3. Tem linhas em branco?

In [8]:
data.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [9]:
data.loc[(data['Year'].isnull()) | (data['Publisher'].isnull())]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
377,378,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49
431,432,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.86,1.02,0.00,0.29,3.17
470,471,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00
607,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53
...,...,...,...,...,...,...,...,...,...,...,...
16427,16430,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01
16493,16496,The Smurfs,3DS,NaN,Action,Unknown,0.00,0.01,0.00,0.00,0.01
16494,16497,Legends of Oz: Dorothy's Return,3DS,2014.0,Puzzle,NaN,0.00,0.01,0.00,0.00,0.01
16543,16546,Driving Simulator 2011,PC,2011.0,Racing,NaN,0.00,0.01,0.00,0.00,0.01
16553,16556,Bound By Flame,X360,2014.0,Role-Playing,NaN,0.00,0.01,0.00,0.00,0.01

4. As variáveis estã armazenadas em uma única coluna?

In [10]:
data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']].head()

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0     41.49     29.02      3.77         8.46         82.74
1     29.08      3.58      6.81         0.77         40.24
2     15.85     12.88      3.79         3.31         35.82
3     15.75     11.01      3.28         2.96         33.00
4     11.27      8.89     10.22         1.00         31.37

<div class="alert alert-warning"> 
<strong><div style="color: rgb(0, 0, 0);">⚠️Observações:</div></strong> <br>

<div style="color: rgb(0, 0, 0);"> -> As linhas em branco serão preenchidas, uma vez que o restante dos dados podem ser utilizados.</div>
<div style="color: rgb(0, 0, 0);"> -> Como há jogos lançados em diferentes anos, mas com mesmo nome, então o nome do jogo será concatenado com o ano.</div>
<div style="color: rgb(0, 0, 0);"> -> O dataset foi "derretido" através das vendas por continente, ou seja, para cada jogo haverá uma linha referente a cada continente.</div>

## Tratamento dos Dados

Pivotar a tabela para que a variável Sales fique em uma única coluna

In [11]:
data_melt = pd.melt(
    data,
    id_vars = ['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher'],
    var_name = 'Continent',
    value_name = 'Sales'
)

In [12]:
data_melt.head()

,Rank,Name,Platform,Year,Genre,Publisher,Continent,Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,NA_Sales,41.49
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,NA_Sales,29.08
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,NA_Sales,15.85
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,NA_Sales,15.75
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,NA_Sales,11.27

<div class="alert alert-warning"> 
<strong><div style="color: rgb(0, 0, 0);">⚠️Observações:</div></strong> <br>

<div style="color: rgb(0, 0, 0);"> ! A partir da alteração anterior, o dataset terá multiplas linhas para um mesmo jogo, pois os continentes foram quebrados em linha.</div>

Renomeação das colunas para português

In [13]:
data_melt.columns = ['id', 'nome', 'plataforma', 'ano', 'genero', 'desenvolvedora', 'continente', 'vendas']

In [14]:
data_melt.head()

,id,nome,plataforma,ano,genero,desenvolvedora,continente,vendas
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,NA_Sales,41.49
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,NA_Sales,29.08
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,NA_Sales,15.85
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,NA_Sales,15.75
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,NA_Sales,11.27

In [15]:
data_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82990 entries, 0 to 82989
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              82990 non-null  int64
 1   nome            82990 non-null  object
 2   plataforma      82990 non-null  object
 3   ano             81635 non-null  float64
 4   genero          82990 non-null  object
 5   desenvolvedora  82700 non-null  object
 6   continente      82990 non-null  object
 7   vendas          82990 non-null  float64
dtypes: float64(2), int64(1), object(5)
memory usage: 5.1+ MB

Substituição das linhas em nulo

In [16]:
data_melt['ano'].fillna(0000, inplace = True)
data_melt['desenvolvedora'].fillna('unknown', inplace = True)

In [17]:
data_melt.isnull().sum()

id                0
nome              0
plataforma        0
ano               0
genero            0
desenvolvedora    0
continente        0
vendas            0
dtype: int64

Criar nova coluna concatenando nome do jogo e ano

In [18]:
# converter em inteiro para retirar o decimal
data_melt['ano'] = data_melt['ano'].astype(int) 

# converter em string para possibilitar a concatenação
data_melt['ano'] = data_melt['ano'].astype(str)

# concatenar
data_melt['nome_ano'] = data_melt['nome'] + ' (' + data_melt['ano'] + ')'

data_melt.head()

,id,nome,plataforma,ano,genero,desenvolvedora,continente,vendas,nome_ano
0,1,Wii Sports,Wii,2006,Sports,Nintendo,NA_Sales,41.49,Wii Sports (2006)
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,NA_Sales,29.08,Super Mario Bros. (1985)
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,NA_Sales,15.85,Mario Kart Wii (2008)
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,NA_Sales,15.75,Wii Sports Resort (2009)
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,NA_Sales,11.27,Pokemon Red/Pokemon Blue (1996)

Classificar corretamente o nome dos continentes a coluna 'continente'

In [19]:
data_melt['continente'].unique()

array(['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype=object)

In [20]:
data_melt['continente'] = data_melt['continente'].map({
    'NA_Sales': 'America do Norte',
    'EU_Sales': 'Europa',
    'JP_Sales': 'Japao',
    'Other_Sales': 'Outros',
    'Global_Sales': 'Total'
    })

## Análise Exploratória de Dados (EDA)

In [21]:
data_melt.describe()

                 id        vendas
count  82990.000000  82990.000000
mean    8300.605254      0.214921
std     4791.738450      0.851977
min        1.000000      0.000000
25%     4151.000000      0.000000
50%     8300.500000      0.030000
75%    12450.000000      0.150000
max    16600.000000     82.740000

In [22]:
data_melt.head()

,id,nome,plataforma,ano,genero,desenvolvedora,continente,vendas,nome_ano
0,1,Wii Sports,Wii,2006,Sports,Nintendo,America do Norte,41.49,Wii Sports (2006)
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,America do Norte,29.08,Super Mario Bros. (1985)
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,America do Norte,15.85,Mario Kart Wii (2008)
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,America do Norte,15.75,Wii Sports Resort (2009)
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,America do Norte,11.27,Pokemon Red/Pokemon Blue (1996)

### Histórico de Vendas por Ano

A quantidade de jogos lançados e o valor arrecadado ao longo dos anos são diretamente proporcionais. A partir dos anos 2000 ambos aumentaram, coincidindo com o lançamento dos video games PS2, XBOX e GameBoy.

In [23]:
data_plot = data_melt.groupby(['ano'])['nome'].nunique()
x = data_plot.index
y = data_plot.values

fig = px.line(
              data_plot,
              x = x, 
              y = y, 
              width = 1200, 
              height = 500,
              markers = True,
              title = 'Jogos Lançados por Ano',
              labels = dict(ano = "Ano de Lançamento", y = "Quantidade de Jogos")
              )

fig.add_annotation(
                  text="                     Jogos sem ano de lançamento",
                  xref = "paper", # referencia de posicao para a anotação
                  yref = "paper",
                  x = 0.06, # posição onde ficará a anotação
                  y = 0.25, 
                  showarrow = True, 
                  arrowsize = 0.7, # tamanho da flecha
                  arrowwidth = 2,
                  arrowhead = 5,
                  xshift = -4.5, # posicao x da flecha
                  yshift = 10, # posicao y da flecha
                  standoff = 5
                  )


fig.update_xaxes(tickangle=45)
fig.show()

In [24]:
data_plot = data_melt[data_melt['continente'] != 'Total'].groupby(['ano', 'continente'])['vendas'].sum()
x = data_plot.index.get_level_values('ano') 
color = data_plot.index.get_level_values('continente')
y = data_plot.values

fig = px.line(
              data_plot,
              x = x, # eixo x
              y = y, # eixo y
              color = color, # legenda
              width = 1200, 
              height = 500,
              markers = True,
              title = 'Valor Arrecadado (em milhões) por Ano e Continente',
              labels = dict(x = "Ano de Lançamento", y = "Valor Arrecadado (Milhões)", color = 'Continente') # alteração das legendas
              )

# adicionar anotação ao gráfico

fig.add_annotation(
                  text = "                           Jogos sem ano de lançamento",
                  xref = "paper", # referencia de posicao para a anotação
                  yref = "paper",
                  x = 0.06, # posição onde ficará a anotação
                  y = 0.2, 
                  showarrow = True, 
                  arrowsize = 0.7, # tamanho da flecha
                  arrowwidth = 2,
                  arrowhead = 5,
                  xshift = -4.5, # posicao x da flecha
                  yshift = 10, # posicao y da flecha
                  standoff = 5,
                  )

# adicionar traço ao percorrer o gráfico com o mouse

fig.update_traces(mode="markers+lines", hovertemplate=None)
fig.update_layout(hovermode="x unified")

# rotacionar eixo e plotar

fig.update_xaxes(tickangle=45)
fig.show()

In [25]:
# primeiro ano de cada plataforma

data_melt_ = data_melt.loc[data_melt['ano'] != '0'] # retirar registros sem ano de lançamento
data_melt_['plataforma_ano_rank'] = data_melt_.groupby('plataforma')['ano'].rank(method = 'dense', ascending = True)

# novo df com o nome das plataformas e seu ano de lançamento

lancamento_plataformas = data_melt_[['plataforma', 'ano']].loc[data_melt_['plataforma_ano_rank'] == 1].drop_duplicates()
lancamento_plataformas.sort_values(by = 'ano', ascending = True, inplace = True)
#lancamento_plataformas.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
data = lancamento_plataformas.groupby('ano')['plataforma'].count()
x = data.index
y = data.values

fig = px.line(
              data,
              x = x, 
              y = y, 
              width = 1200, 
              height = 500,
              markers = True,
              title = 'Plataformas Lançadas por Ano',
              labels = dict(ano = "Ano de Lançamento", y = "Quantidade de Plataformas"),
              line_shape='spline'
              )

fig.show()

In [28]:
fig = go.Figure(data = [go.Table(
    columnorder = [2,1],
    header = dict(values = list(lancamento_plataformas.columns)),
    cells = dict(values = [lancamento_plataformas.plataforma, lancamento_plataformas.ano])
)])

fig.update_layout(width=350, height=500)
fig.show()

### Vendas por Tipo de Jogo

Os jogos que mais arrecadam dinheiro são de Ação, Esportes, Tiro, RPG e Plataforma

In [59]:
data_melt[data_melt['continente'] != 'Total'].groupby(['genero'])['vendas'].sum().nlargest(5)

genero
Action          1750.16
Sports          1330.54
Shooter         1036.84
Role-Playing     927.26
Platform         831.04
Name: vendas, dtype: float64

In [60]:
data_plot = data_melt[data_melt['continente'] != 'Total'].groupby(['ano', 'genero'])['vendas'].sum()
x = data_plot.index.get_level_values('ano') 
color = data_plot.index.get_level_values('genero')
y = data_plot.values

fig = px.bar(
              data_plot,
              x = x,
              y = y, 
              color = color,
              width = 1200, 
              height = 500,
              title = 'Valor Arrecadado (em milhões) por Ano e Genero',
              labels = dict(x = "Ano de Lançamento", y = "Valor Arrecadado (Milhões)", color = 'Genero'),
              color_discrete_map= {'Action': 'brown',
                                   'Sports': 'blue',
                                   'Shooter': 'red',
                                   'Misc': 'grey',
                                   'Role-Playing': 'green',
                                   'Adventure': 'grey',
                                   'Racing': 'grey',
                                   'Platform' : 'purple',
                                   'Simulation': 'grey',
                                   'Strategy': 'grey',
                                   'Puzzle': 'grey',
                                   'Fighting': 'grey'
                                   }
              )

fig.update_xaxes(tickangle=45)
fig.show()

In [62]:
pio.renderers

Renderers configuration
-----------------------
    Default renderer: 'colab'
    Available renderers:
        ['plotly_mimetype', 'jupyterlab', 'nteract', 'vscode',
         'notebook', 'notebook_connected', 'kaggle', 'azure', 'colab',
         'cocalc', 'databricks', 'json', 'png', 'jpeg', 'jpg', 'svg',
         'pdf', 'browser', 'firefox', 'chrome', 'chromium', 'iframe',
         'iframe_connected', 'sphinx_gallery', 'sphinx_gallery_png']